import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CustomPage from "@jektis/components/generic/CustomPage";
import Center, { Axes } from "@jektis/components/generic/center";
import Header from "@jektis/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <CustomPage>
          <Center axe={Axes.x}>
            <Header />
          </Center>
          <div className="px-12 w-full">{children}</div>
        </CustomPage>
      </body>
    </html>
  );
}
