import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CustomPage from "@jektis/components/generic/CustomPage";
import Center, { Axes } from "@jektis/components/generic/center";
import Header from "@jektis/components/layout/header";
import Footer from "@jektis/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jektis Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <CustomPage>
          <Center axe={Axes.x}>
            <div className="w-full lg:mb-0 mb-20">
              <Header />
            </div>
          </Center>
          <div className="px-2 w-full">{children}</div>
          <div className="w-full mt-12 mb-8 pl-4">
            <Footer />
          </div>
        </CustomPage>
      </body>
    </html>
  );
}
